In [1]:
import math
import numpy as np
from utils import *

%load_ext autoreload
%autoreload 2

In [2]:
sigmoid(np.array([1,2,3,4,5,7]))

array([0.73105858, 0.88079708, 0.95257413, 0.98201379, 0.99330715,
       0.99908895])

In [3]:
x = np.array([1, 2, 3])
sderiv = sigmoid_deriv(x)
print(f'Sigmoid Derivative : {sderiv}')

Sigmoid Derivative : [0.19661193 0.10499359 0.04517666]


In [4]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
image = image2vec(image)
image.shape

(18, 1)

In [6]:
normalized_row(np.array([
     [0, 3, 4],
    [1, 6, 4]
]))

array([[0.        , 0.6       , 0.8       ],
       [0.13736056, 0.82416338, 0.54944226]])

In [7]:
normalized_row(
    np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
)

array([[0.85811633, 0.19069252, 0.47673129, 0.        , 0.        ],
       [0.81373347, 0.58123819, 0.        , 0.        , 0.        ]])

In [14]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

np.sum(np.abs(yhat-y))

yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

np.sum(np.square(np.abs(yhat-y)))
# print("L1 = " + str(L1(yhat,y)))

0.43

In [ ]:
# def compute_cost(Yhat, Y):
    nY - Yhat
    